#!/bin/sh

set -e

case "$1" in
        configure)
		#check whether libglx.so got installed.  some releases earlier than x740
		#will not actually have this libglx.so
		if [ ! -f /usr/lib/xorg/modules/extensions/libglx.so ]; then
			dpkg-divert --remove --rename --package xorg-driver-fglrx --divert /usr/lib/fglrx/libglx.so.xlibmesa /usr/lib/xorg/modules/extensions/libglx.so > /dev/null
		fi

esac

if [ "$1" = "configure" ]; then
	ldconfig
fi

#DEBHELPER#
