#!/bin/sh
#
# Copyright (c) 2010-2014 Sebastian Siebert (freespacer@gmx.de)
# All rights reserved.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Set local language always to C
export LC_ALL=C
export LANG=C

if [ "$(whoami)" != "root" ]; then
    echo "Must be root to run this script." 1>&2
    exit 1
fi

if [ $# -ge 2 ]; then
    echo "Usage: $(basename $0) <amd|intel|query>" 1>&2
    echo "Please choose one parameter" 1>&2
    exit 1
fi

ARCH=`uname -m`
case "${ARCH}" in
    i?86)
        LIB="lib"
    ;;
    x86_64)
        LIB="lib64"
    ;;
esac

function switch_to_amd() {

    if [ -f /usr/${LIB}/libGL.so.1.2.0 ]; then
        OPENGL_VERSION="1.2.0"
        ln -snf /usr/X11R6/${LIB}/fglrx/fglrx-libGL.so.1.2 \
                /usr/X11R6/${LIB}/libGL.so.1.2.0
        ln -snf libGL.so.1.2.0 /usr/X11R6/${LIB}/libGL.so.1.2
    elif [ -f /usr/${LIB}/libGL.so.1.2 ]; then
        OPENGL_VERSION="1.2"
        ln -snf /usr/X11R6/${LIB}/fglrx/fglrx-libGL.so.1.2 \
                /usr/X11R6/${LIB}/libGL.so.1.2
    fi
    ln -snf libGL.so.1.2 /usr/X11R6/${LIB}/libGL.so.1
    ln -snf libGL.so.1 /usr/X11R6/${LIB}/libGL.so
    /sbin/ldconfig /usr/X11R6/${LIB}
    if [ "${LIB}" = "lib64" ]; then
        if [ "${OPENGL_VERSION}" = "1.2.0" ]; then
            ln -snf /usr/X11R6/lib/fglrx/fglrx-libGL.so.1.2 \
                    /usr/X11R6/lib/libGL.so.1.2.0
            ln -snf libGL.so.1.2.0 /usr/X11R6/lib/libGL.so.1.2
        elif [ "${OPENGL_VERSION}" = "1.2" ]; then
            ln -snf /usr/X11R6/lib/fglrx/fglrx-libGL.so.1.2 \
                    /usr/X11R6/lib/libGL.so.1.2
        fi
        ln -snf libGL.so.1.2 /usr/X11R6/lib/libGL.so.1
        ln -snf libGL.so.1 /usr/X11R6/lib/libGL.so
        /sbin/ldconfig /usr/X11R6/lib
    fi

}

function switch_to_intel() {

    if [ -f /usr/${LIB}/libGL.so.1.2.0 ]; then
        OPENGL_VERSION="1.2.0"
        ln -snf /usr/${LIB}/libGL.so.1.2.0 \
                /usr/X11R6/${LIB}/libGL.so.1.2.0
        ln -snf libGL.so.1.2.0 /usr/X11R6/${LIB}/libGL.so.1.2
    elif [ -f /usr/${LIB}/libGL.so.1.2 ]; then
        OPENGL_VERSION="1.2"
        ln -snf /usr/${LIB}/libGL.so.1.2 \
                /usr/X11R6/${LIB}/libGL.so.1.2
    fi
    ln -snf libGL.so.1.2 /usr/X11R6/${LIB}/libGL.so.1
    ln -snf libGL.so.1 /usr/X11R6/${LIB}/libGL.so
    /sbin/ldconfig /usr/X11R6/${LIB}
    if [ "${LIB}" = "lib64" ]; then
        if [ "${OPENGL_VERSION}" = "1.2.0" ]; then
            ln -snf /usr/lib/libGL.so.1.2.0 \
                    /usr/X11R6/lib/libGL.so.1.2.0
            ln -snf libGL.so.1.2.0 /usr/X11R6/lib/libGL.so.1.2
        elif [ "${OPENGL_VERSION}" = "1.2" ]; then
            ln -snf /usr/lib/libGL.so.1.2 \
                    /usr/X11R6/lib/libGL.so.1.2
        fi
        ln -snf libGL.so.1.2 /usr/X11R6/lib/libGL.so.1
        ln -snf libGL.so.1 /usr/X11R6/lib/libGL.so
        /sbin/ldconfig /usr/X11R6/lib
    fi

}

function get_current_driver() {

    if [ -f /usr/${LIB}/libGL.so.1.2.0 ]; then
        LIB_LINK="`readlink /usr/X11R6/${LIB}/libGL.so.1.2.0 2>/dev/null`"
    elif [ -f /usr/${LIB}/libGL.so.1.2 ]; then
        LIB_LINK="`readlink /usr/X11R6/${LIB}/libGL.so.1.2 2>/dev/null`"
    fi

    if [ "${LIB_LINK}" = "/usr/X11R6/${LIB}/fglrx/fglrx-libGL.so.1.2" ]; then
        echo "amd"
    elif [ "${LIB_LINK}" = "fglrx/fglrx-libGL.so.1.2" ]; then
        echo "amd"
    elif [ "${LIB_LINK}" = "/usr/${LIB}/libGL.so.1.2.0" ]; then
        echo "intel"
    elif [ "${LIB_LINK}" = "/usr/${LIB}/libGL.so.1.2" ]; then
        echo "intel"
    else
        echo "unknown"
    fi

}

case "$1" in
    amd)
        echo "Switch to AMD" 1>&2
        switch_to_amd
    ;;
    intel)
        echo "Switch to Intel" 1>&2
        switch_to_intel
    ;;
    query)
        get_current_driver
    ;;
    *)
        echo "Usage: $(basename $0) <amd|intel|query>" 1>&2
        exit 1
    ;;
esac

exit 0
